[FEATURE#53794] EntityUtils
etna-alternance/composer-lib-utils pull request #10
Opened 2017-05-30 08:06 UTC by TinyTinyKame

- Ajout d'une fonction permettant de récupérer les différences entre 2 entités

2017-05-30 08:50 UTC, lapwil approved these changes
OK je l'aurai ptet plutôt appelé getChanges mais ça me va aussi

2017-05-30 12:15 UTC, TinyTinyKame commented
Je peux changer le nom, mais faut que je rajoutes les tests, etc.., la fonction est fini mais la PR ne l'est pas

2017-05-30 12:16 UTC, staciekith commented on README.md
> +- `EntityUtils::getDiff` Effectue la comparaison entre 2 tableaux et renvoie les différences
Est-ce qu'il faudrait pas préciser que ça doit être des tableaux de string du coup ? (pas d'array, ni d'objets)

2017-06-01 07:34 UTC, gdubost commented on src/EntityUtils.php
> +        );
Je la trouve effrayante ta fonction la, et pourquoi n'utilises tu pas la fonction `empty` en PHP ?

2017-06-01 09:28 UTC, TinyTinyKame commented on src/EntityUtils.php
> +        );
Pour le coup, j'ai testé avec `empty` et certains cas ne sont pas couverts, donc je reste sur ça

2017-06-01 14:32 UTC, gdubost approved these changes

2017-06-05 12:32 UTC, gdubost commented
En vrai, je le mettrai dans un autre composant ce utils

2017-06-05 12:33 UTC, lapwil requested changes
juste ça

2017-06-05 12:33 UTC, lapwil commented on src/EntityUtils.php
> +     * @param  array $new
manque quelques `@params`

2017-06-05 12:33 UTC, lapwil commented on README.md
> +- `EntityUtils::getDiff` Effectue la comparaison entre 2 tableaux et renvoie les différences
du coup c'est getChanges maintenant

2017-06-05 12:39 UTC, staciekith approved these changes

2017-06-05 12:40 UTC, Kumatetsu commented on Tests/Functional/features/entity/changes.feature
> +        "* Changement du maybe 'i came on too strong'' => 'i waited too long'",
après strong t'as deux `''`

2017-06-05 12:40 UTC, Kumatetsu commented on Tests/Functional/features/entity/changes.feature
> +        "* Changement du maybe 'i came on too strong'' => 'i waited too long'",
pareil

2017-06-05 12:40 UTC, Kumatetsu commented on Tests/Functional/features/entity/changes.feature
> +        "* Changement de peut-être 'i came on too strong'' => 'i waited too long'",
pareil

2017-06-06 12:10 UTC, staciekith approved these changes
Okay

2017-06-07 09:25 UTC, lapwil approved these changes
OK

2017-06-07 13:08 UTC, Kumatetsu approved these changes
OK

2017-06-07 15:58 UTC, TinyTinyKame commented
Je fais dans un autre repo !

2017-06-07 15:58 UTC, closed without merging