[Feature/38771] Ajout du CC re@etna dans la lib-utils
etna-alternance/composer-lib-utils pull request #8
Opened 2016-11-18 14:25 UTC by misseur

- On rajoute ` re@etna-alternance.net ` à chaque envoi de mail si il n'y est pas déjà.
- Suppression d'un context qui était en doublon avec composer-behat-utils
- Rajout d'une option d'envoi de mail au context de test pour tester les mails en cc
- Ajout de tests associés

2016-11-21 10:12 UTC, TinyTinyKame requested changes

2016-11-21 10:12 UTC, TinyTinyKame commented on src/NotifyUtils.php
> +        if (false === isset($mail["cc"])) {
tu peux revoir ce `if`

2016-11-21 14:25 UTC, lennuyp commented on Tests/Functional/Context/FeatureContext.php
>          $mail_opt = [];
T'es obligé de le déclarer ici une première fois ?

2016-11-21 14:26 UTC, lennuyp commented on Tests/Functional/features/notify/email.feature
> +Scénario: Envoyer un email avec plusieur copie de mail
plusieurs*

2016-11-22 08:30 UTC, misseur commented on Tests/Functional/Context/FeatureContext.php
>          $mail_opt = [];
Oui, sinon au moment d'appeler sendEmail ligne 116 il ne sera pas défini.

2016-11-22 09:58 UTC, TinyTinyKame commented
Je crois pas que ça soit vraiment une bonne idée de mettre toujours l'émetteur en copie, je pense qu'il faut que ça soit propre à chaque API cette décision, car tu changes la lib-utils, du coup, tu vas changer le comportement de toutes les autres APIs alors qu'on veut pas forcément toujours mettre l'émetteur en copie, je pense par exemple aux crons

2016-11-22 10:53 UTC, misseur commented
@TinyTinyKame : Oui tu as raison.

J'ai fais cette PR suite au ticket : https://tickets.etna-alternance.net/admin/#/task/38771 .
Guillaume aussi réfléchis si dans le fond on veut vraiment faire ça, et voir si il y a pas des cas où on veut vraiment pas de ce cc.

Du coup j'ai fais cette PR pour la forme. Il faut encore regarder les cas particuliers pour voir si la logique convienne partout. Vue que cette PR est sur la V2, ça incombe déjà moins d'appli.

Après, pour revenir sur l'exemple des crons, cela peut être une bonne chose d'avoir un cc. Quand il y a un bug du coup, nous avons directement le mail avec les donnés en extract, où autre, ce qui peut nous faire gagner pas mal de temps.
Mais c'est sans doute vrai qu'il y a des cas particuliers, du coup à voir.

Dans tous les cas, cela peut attendre un peu.

2017-01-09 11:00 UTC, closed without merging